version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: zik-redis
    restart: always
    expose:
      - 6379
    networks:
      - zik

  backend:
    build: ./backend/
    container_name: zik-backend
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    restart: always
    ports:
      - "127.0.0.1:8663:5000"
    networks:
      - zik

  frontend:
    build: ./frontend/
    container_name: zik-frontend
    depends_on:
      - backend
    ports:
      - "127.0.0.1:8662:80"
    restart: always
    networks:
      - zik

  mysql:
    image: mysql:latest
    container_name: zik-mysql
    restart: always
    environment:
      MYSQL_DATABASE: "zik"
      MYSQL_USER: "zik"
      MYSQL_PASSWORD: "w33w00tH1s1sS3cr3t"
      MYSQL_ROOT_PASSWORD: "L3Z1klEzIkLeZiK"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    volumes:
      - ./mysql/data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - zik

networks:
  zik:
    driver: bridge
